# Generated by Django 3.0.3 on 2020-03-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200305_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imgage',
            new_name='image',
        ),
    ]
